#Jekyll config file

#title of site
name: Ben Balter

#description of site
description: "GitHubber, Gov 2.0 Evangelist, Aspiring Attorney"

#URL of site, include http://, do not include a trailing slash
url: http://ben.balter.com

#files to exclude, array
exclude: [ 'readme.md', 'php', 'node_modules', 'Gruntfile.coffee', 'package.json' ]

#posts per page
paginate: 10

#number of items in RSS feed
rss_limit: 10

#permalink structure, see https://github.com/mojombo/jekyll/wiki/Permalinks
permalink: /:year/:month/:day/:title/

#prose config, see http://prose.io/help/handbook.html
prose:
  siteurl: "http://ben.balter.com"
  media: assets/img
  relativeLinks: http://ben.balter.com/links.jsonp
  metadata:
    _posts:
      - name: categories
        field:
          label: Categories
          element: select
          placeholder: Select a category
          options:
            - name: Technology
              value: technology
            - name: Business
              value: business
            - name: Law
              value: law
      - name: layout
        field:
          element: hidden
          value: post
      - name: title
        field:
          element: text
          label: Title
          value: ""
      - name: excerpt
        field:
          element: text
          label: Excerpt
          value: ""       
      - name: author
        field:
          element: text
          label: Author
          value: Ben Balter
      - name: comments
        field:
          element: checkbox
          label: Comments Enabled
          value: true
      - name: tags
        field: 
          element: text
          label: Tags
          value: ""
    "/":
      - name: title
        field:
          element: text
          label: Title
          value: ""
      - name: excerpt
        field:
          element: text
          value: ""
      - name: id
        field:
          element: text
          value: ""
      - name: layout
        field:
          element: select
          placeholder: Select a layout
          options:
            - name: Page
              value: page
            - name: Home
              value: home
            - name: Default
              value: default
            - name: Resume
              value: resume

#Twitter Widget
twitter: 
  username: "benbalter"
  count: 5

#disqus widget
disqus:
  shortname: 'benbalter'
  count: 5
  api_key: "OQ5OlN2AtWDfIQ0bjIGwdfq9SsEB3P8NdzhYTRak7R45KeAD744aVIqJZDYqvmuL"

#google analytics username
ga_username: 'UA-18088627-1'

#build config
pygments: true
markdown: kramdown